---
title: "텐서플로우 MNIST 테스트를 R로 진행해보기"
author: "eunkwang"
date: '2017 8 27 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R을 이용하여 텐서플로우를 이용한 MNIST 모델링을 진행하고자 함
아래 코드는 RstudioForR 사이트의 코드를 참고하여 진행하였음

## 라이브러리 및 데이터 로드

```{r}
library(tensorflow)
datasets <- tf$contrib$learn$python$learn$datasets
mnist <- datasets$mnist$read_data_sets("MNIST-data", one_hot = TRUE)
```


## 초기 변수의 설정

```{r}
x <- tf$placeholder(tf$float32, shape(NULL, 784L))
W <- tf$Variable(tf$zeros(shape(784L, 10L)))
b <- tf$Variable(tf$zeros(shape(10L)))
y <- tf$nn$softmax(tf$matmul(x, W) + b)
y_ <- tf$placeholder(tf$float32, shape(NULL, 10L))

#gpu를 이용하여 학습하려면 다음과 같이 with 로 디바이스를 지정하면됨
#cpu 연산과 gpu 연산의 값이 다름
with({tf$device('/cpu:0')},{
  cross_entropy <- tf$reduce_mean(-tf$reduce_sum(y_ * tf$log(y), reduction_indices=1L))
  optimizer <- tf$train$GradientDescentOptimizer(0.5)
})

train_step <- optimizer$minimize(cross_entropy)
init <- tf$initialize_all_variables()
```


## 모델링

```{r}
sess <- tf$Session()
sess$run(init)

# 1000회 반복 학습
for (i in 1:1000) {
  batches <- mnist$train$next_batch(100L)
  batch_xs <- batches[[1]]
  batch_ys <- batches[[2]]
  sess$run(train_step,
           feed_dict = dict(x = batch_xs, y_ = batch_ys))
}

```

## 모델 성능 평가

```{r}
correct_prediction <- tf$equal(tf$argmax(y, 1L), tf$argmax(y_, 1L))
accuracy <- tf$reduce_mean(tf$cast(correct_prediction, tf$float32))
sess$run(accuracy, feed_dict=dict(x = mnist$test$images, y_ = mnist$test$labels))
```

